[workspace]
[package]
version = "0.1.0"
name = "omni-account-zkp-script"
edition = "2021"

[dependencies]
sp1-sdk = "1.1.1"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }